apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgres.yaml

configMapGenerator:
- files:
  - init.sql
  - 01-init-db.sh=init-db.sh
  name: postgres-init
labels:
- includeSelectors: true
  pairs:
    app: postgresql
